### ISSUE TITLE
Consider handling booleans

### ISSUE THREAD

**Issue by bebraw** [trevorblades/use-query-string#2]
I think the idea of the hook is great and I use a similar pattern myself. One addition that might be useful is handling of booleans and serializing them to/from the query. I imagine number might be another type to consider and if you go this route, maybe it means there should be a schema to describe the data model so it can be serialized nicely.

**Comment by trevorblades** [comment]
This is a great idea @bebraw! I just made a change that adds an optional third argument to the hook, allowing you to pass along options like `parseNumbers` or `parseBooleans` to the parser we're using.

You can read more about this feature here: https://github.com/trevorblades/use-query-string#parser-configuration

Let me know if this change suits your needs!
