### ISSUE TITLE
setQuery doesn't reset the query state

### ISSUE THREAD

**Issue by noor-ul-amin0** [trevorblades/use-query-string#22]
`setQuery(), setQuery({}) ` doesn't reset to the default state.
I have a button upon clicking i want to remove all the query strings in the url, what i do is `setQuery()/setQuery({})` but it doesn't reset it at all.

**Comment by love-nltg** [comment]
Late to the party, but what you probably want to do is

```
setQuery(Object.fromEntries(Object.keys(query).map((key) => [key, undefined])))
```

**Comment by noor-ul-amin0** [comment]
@love-nltg thank you
